development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: outlook_db
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: outlook_db
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: outlook_db
  username: root
  password: root
  #host: stage.theamp.com
